---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: leelavathicts/kaniko-project:executor_v1.6.0-debug 
    args:
      - "--context=git://github.com/subbussmeo/kaniko-demo"
      - "--destination=subbu7898/kaniko:latest"
    env:
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            name: git-token
            key: GIT_TOKEN
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
  - name: docker-config
    secret:
      secretName: docker-credentials
      items:
          - key: .dockerconfigjson
            path: config.json